---
Experiment:
  resnet_path: 
  latent_dim: 4096
  cls_dim: 2048
  feat_dim: 2048
  att_size: 1024
  image_size: 448
  seen_classes: 82
  nclasses: 102
  device: "cuda:0"
  random_grouping: true
  random_crop: true
  train_id: 1
  nepoch: 30
  manualSeed: 3131
Model:
  vars_test: false
  NAA_test: true
  batch_size: 32
  pretrain_epoch: 1
  unfix_low: true
  unfix_high: true
  unfix_vars: true
  train_beta: false
Hyperparameters:
  t: 5
  gamma: 2
  delta: 0.5
  alpha1: 1.0
  alpha2: 0.1
  alpha3: 1.0
  alpha4: 1.0
  alpha5: 0.1
  alpha6: 0.0
  alpha7: 0.0
  Lp1: 10
  pretrain_lr: 0.0001
  classifier_lr: 0.000001
